title: PiPsPlaza
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2473118
  brandStrength: 0.7939068
  lightness: 0.9820789
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  rhythmicContrast: 0.625448
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: PipsPlaza
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1182796
layout_spectrum: 0.9354839
